# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: be1bb6be5bb7508373501bf68c925e2f74a1fe9a758ce9409e430714d642cdcb329da4efaa930b811169d7cfca3326ead6d34a531d0e1b2472b942d4bd9f822b

test:
  secret_key_base: e1bc07bcba611447017bd8595315cc7f39e99cc57f097f90aed45f89f1860d6a29649726a8e87592aa876dbb2c75088b49e79630d9ea02c5f0b841deaab47322

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
